name: Development

on:
  push:
    branches: [ master ]
  # 手动触发
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install

      - name: Build blog
        run: |
         echo "::group::build"
         yarn build
         echo "::endgroup::"

         echo "::group::./ files"
         ls -al
         echo "::endgroup::"

         echo "::group::./public files"
         ls -al ./public
         echo "::endgroup::"

      # 同步文件
      - name: Deploy static files to Tencent CloudBase
        run: |
          echo "::group::tcb login"
          yarn tcb login --apiKeyId ${{ secrets.SECRET_ID }} --apiKey ${{ secrets.SECRET_KEY }}
          echo "::endgroup::"

          echo "::group::tcb hosting detail"
          yarn tcb hosting detail -e ${{ secrets.ENV_ID }}
          echo "::endgroup::"

          echo "::group::tcb hosting deploy"
          yarn tcb hosting deploy ./public / -r gz -e ${{ secrets.ENV_ID }}
          echo "::endgroup::"
